config/routes.rb
Poesearch::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root to: "searches#new"

  resources :users, except: [:index] do
    member do
      post :generate_token
      get :link_character
      post :validate_account
    end
    collection do
      get :update_layout
    end
    resource :account
  end

  resources :searches, except: [:edit] do
    collection do
      get :favorite, as: :favorite
    end
  end

  resources :searches, except: [:edit]
  [:weapons, :armours, :misc].each do |type|
      resources :"#{type.to_s.singularize}_searches", except: [:edit]
  end

  resources :similar_searches

  resources :items, only: [:index, :show, :destroy] do
    member do
      post    :add_to_cart
      delete  :remove_from_cart
      post    :verify
    end
  end

  resource :shopping_cart

  resources :authentications, only: [:create, :destroy]

  resources :messages

  resources :players do
    member do
      put :mark_online
      put :mark_offline
    end
  end

  resources :accounts

  namespace :admin do
    root to: "admin#index"
    resources :searches
    resources :broadcasts
    resources :messages, only: [:index, :show]
    resources :scrawls
  end


  resources :exile_searches, path: "/exiles/search"

  resources :exiles do
    member do
      put :vote_up
    end
    collection do
      post :load_votes
    end
  end

  resources :forum_threads, path: "/threads", only: [:show]

  get "/feedback",  to: "feedback#index", as: :feedback
  get "/about/item_prices", to: "about#item_prices", as: :item_prices
  get "/about/search_by_price", to: "about#search_by_price", as: :search_by_price
  get "/about/faq", to: "about#faq", as: :faq

  match '/auth/:provider/callback' => 'authentications#create', via: :get
end

app/models/exile.rb
class Exile < ActiveRecord::Base
  include ExileExtensions::Mapping

  GEAR_TYPES = [:helmet, :main_weapon, :offhand_weapon, :body_armour, :gloves, :belt, :boots]

  belongs_to :user
  belongs_to :klass

  has_many :exile_uniques
  has_many :uniques, through: :exile_uniques

  store :cached_photos, accessors: [:photos, :cover], coder: JSON
  store :items, accessors: [GEAR_TYPES], coder: JSON

  attr_accessible :name, :tagline, :description, :album_uid, :video_uid, :gear_description,
    :klass_id, :unique_ids,
    :helmet, :main_weapon, :offhand_weapon, :body_armour, :gloves, :belt, :boots

  before_validation :set_album_uid, if: :album_uid_changed?

  attr_accessor :update_album
  def update_album?; update_album end
  before_save :cache_photos, if: :update_album?

  class ImgurAlbumValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      if value.present? && !value.match(/[A-Za-z0-9]+/)
        record.errors[attribute] << "The Imgur album is invalid"
      end
    end
  end
  validates :album_uid, presence: true, imgur_album: true
  validates :name, presence: true
  validates :klass, presence: true
  validates :tagline, presence: true, length: { maximum: 128 }
  validates :description, length: { maximum: 3000 }

  delegate :login, to: :user, prefix: true, allow_nil: true
  delegate :name, to: :klass, prefix: true

  make_voteable

  def to_params
    "#{id}-#{name.parameterize}"
  end

  def cover(size = nil)
    c = cached_photos["cover"]
    return c if size.blank? || c.blank?
    resized_photo(c, size)
  end
  def large_cover; cover(:l) end

  def photos(size = nil)
    return cached_photos["photos"] if size.blank?
    cached_photos["photos"].map do |photo|
      resized_photo(photo, size)
    end
  end

  def resized_photo(photo, size)
    parts = photo.split(".")
    parts[-2] << size.to_s
    parts.join(".")
  end

  def gear
    GEAR_TYPES.map do |type|
      next unless (name = send(type)).present?
      { type: type.to_s.titleize, name: name }
    end.compact
  end

  def any_photos?
    photos && photos.any?
  end

  private


  def set_album_uid
    return unless album_uid.present?

    uid = album_uid.split("/").last.match(/([A-Za-z0-9]+)/).try :[], 0
    return unless uid

    write_attribute(:album_uid, uid)
  end

  def cache_photos
    if album = Imgur::Album.find_by_id(album_uid)
      self.photos = album.image_links
      self.cover = album.cover_link
    end
  end
end

app/controllers/exiles_controller.rb
class ExilesController < ApplicationController
  layout :layout

  respond_to :html, :json

  before_filter :view_layout, only: [:new, :show]

  before_filter :authorize_create, only: [:new, :create, :vote_up]
  before_filter :find_exile, only: [:show, :edit, :update, :destroy, :vote_up]
  before_filter :set_update_album, only: [:update, :vote_up]
  before_filter :authorize_update, only: [:edit, :update, :destroy]

  def index
    redirect_to exile_searches_url
  end

  def new
    @exile = Exile.new
  end

  def edit
  end

  def show
    session[:view_exile] ||= []
    if !session[:view_exile].include? @exile.id
      session[:view_exile] << @exile.id
      @exile.update_column(:views, @exile.views.to_i + 1)
      @exile.update_index if rand(5) == 0
    end

    @next_exile = Exile.where('id > ?', @exile.id).limit(1).first
    @prev_exile = Exile.where('id < ?', @exile.id).order('id DESC').limit(1).first
  end

  def create
    @exile = Exile.create(exile_params) do |exile|
      exile.user = current_user
      exile.update_album = true
    end

    if @exile.errors.any?
      render :edit
    else
      respond_with @exile
    end
  end

  def update
    @exile.update_attributes(exile_params)

    respond_with @exile
  end

  def destroy

  end

  def vote_up
    current_user.up_vote!(@exile)
    respond_with @exile do |format|
      format.json { render json: { count: @exile.votes } }
    end
  end

  def load_votes
    if user_signed_in? && (ids = params[:ids]) && ids.any?
      votes = MakeVoteable::Voting.where(
        voteable_type: "Exile", voteable_id: ids,
        voter_id: current_user.id
      ).map do |v|
        { id: v.voteable_id, upvote: v.up_vote }
      end
    else
      votes = {}
    end

    respond_with @exile do |format|
      format.json { render json: { votes: votes } }
    end
  end

  private

  def exile_params
    params[:exile]
  end

  def find_exile
    @exile = Exile.find(params[:id])
  end

  def authorize_update
    authorize! :update, @exile
  end

  def authorize_create
    authorize! :create, Exile
  end

  def set_update_album
    @exile.update_album = true
  end

  def layout
    if action_name == "show"
      "exile_show"
    else
      "exiles"
    end
  end
end

app/views/exiles/_form.html.erb
<div id="main-content">

  <%= simple_form_for @exile do |f| %>
  <div class="row-fluid">
    <div class="exile span6">
      <div class="box-content">
        <h2>Basic info</h2>

        <div class="control-group">
        <%= f.input :name, input_html: { class: "span12" } %>
        </div>

        <div class="control-group">
        <%= f.input :tagline, as: :string, input_html: { class: "span12" } %>
        </div>

        <div class="control-group">
        <%= f.input :album_uid,
          label: "Imgur album",
          input_html: { class: "span12" }
        %>

        <p class="faded">
          <% if @exile.new_record? %>
            Enter the URL or the id of an Imgur album. Ex: http://imgur.com/a/19jWK
          <% else %>
            To update the screenshot gallery on PoExplorer, just update
            your Imgur album, and re-save your Exile.
          <% end %>
        </p>
        </div>

        <div class="control-group">
        <%= f.label :klass_id, label: "Class", required: true %>
        <%= f.input :klass_id,
          label: false,
          as: :select,
          selected: f.object.klass_id,
          collection: Klass.pluck(:id, :name).map { |k| [k[1], k[0]] },
          input_html: { class: "span12" },
          wrapper_html: { class: "clearfix" } %>
        </div>

        <%= f.input :description, input_html: { class: "span12", style: "height: 128px;" } %>

      </div>
    </div>

    <div class="exile span6">
      <div class="box-content clearfix">
        <h2>Gear <span class="faded small">(optional)</span></h2>

        <div class="bordered-section">
          <%= gear_description(f) %>
        </div>

        <div class="bordered-section">
          <%= f.association :uniques, placeholder: "Select uniques" %>
        </div>

        <label>Generic gear</label>
        <% main_weapons = G_BASE_NAMES["weapon"].values.flatten %>
        <%= gear_input(f, :helmet, G_BASE_NAMES["armour"]["helmet"]) %>
        <%= gear_input(f, :main_weapon, main_weapons) %>
        <%= gear_input(f, :offhand_weapon, main_weapons) %>
        <%= gear_input(f, :body_armour, G_BASE_NAMES["armour"]["body_armour"]) %>
        <%= gear_input(f, :belt, G_BASE_NAMES["misc"]["belt"]) %>
        <%= gear_input(f, :gloves, G_BASE_NAMES["armour"]["glove"]) %>
        <%= gear_input(f, :boots, G_BASE_NAMES["armour"]["boot"]) %>
      </div>
    </div>
  </div>

  <div class="row-fluid">
  <div class="exile span12">
    <div class="box-content">
      <%= f.button :submit, class: "btn-success" %>
    </div>
  </div>
  </div>

  <% end %>

</div>

<% content_for :dom_ready do %>
  $("select").select2({
    allowClear: true
  });
<% end %>

<% content_for :head do %>
  <style type="text/css">
    .input.select { padding: 5px 0; }
  </style>
<% end %>

app/views/exiles/_result.html.erb
<div class="span4 exile result" data-vote="base" data-id="<%= exile.id %>">
  <%= link_to exile_path(exile) do %>
    <div class="cover">
      <div class="faded-background" style="background-image: url(<%= exile.large_cover %>)">
        <div class="overlay"></div>
      </div>
      <h3>
        <%= content_tag :span, data: {
          vote: "button",
          url: user_signed_in? ? vote_up_exile_path(exile) : new_user_registration_path,
          login: !user_signed_in?
        }, class: "border-button" do %>
          <b data-vote-count><%= exile.up_votes %></b> <i class="fa fa-caret-up"></i>
        <% end %>
        <%= exile.name %>
      </h3>
    </div>
  <% end %>

  <% if exile.tagline.present? %>
    <section class="tagline">
      <p><%= exile.tagline %></p>
    </section>
  <% end %>

  <section>
    <%= exile.klass_name %>
  </section>

  <footer>
    <div class="right">by <%= exile.user_login %></div>

    <%= content_tag :span, data: {
          vote: "button",
          url: user_signed_in? ? vote_up_exile_path(exile) : new_user_registration_path,
          login: !user_signed_in?
        } do %>
          <i class="fa fa-caret-up"></i> Upvote!
    <% end %>
    &middot;
    <span>
      ~ <%= exile.views.to_i %> <i class="fa fa-eye"></i>
    </span>
  </footer>
</div>

app/views/exiles/_sub_header.html.erb
<%# javascript "exiles" %>
<% content_for :h1 do %>
  <%= link_to "Exiles", exiles_path %>
<% end %>

<% content_for :main_menu do %>
  <li class="tab-search">
    <%= link_to exiles_path do %>
      <i class="fa fa-align-justify"></i> Browse
    <% end %>
  </li>
  <li class="tab-add-exile">
    <%= link_to "<i class='fa fa-plus'></i> Submit new exile".html_safe, new_exile_path %>
  </li>
<% end %>

app/views/exiles/edit.html.erb
<%= render "form" %>

app/views/exiles/new.html.erb
<%= render "form" %>

app/views/exiles/show.html.erb
<div data-model="base" data-id="<%= @exile.id %>">

<% content_for :side_cover do %>

  <div id="intro">
    <p>
      By <%= @exile.user_login %>
    </p>
  </div>

  <div id="vote" data-vote="base">
    <%= content_tag :div,
      data: {
        url: user_signed_in? ? vote_up_exile_path(@exile) : new_user_registration_path,
        vote: "button",
        login: !user_signed_in?
      },
      class: 'border-button stat' do %>
      <span class="value">
        <span data-vote-count><%= @exile.up_votes %></span>
        <i class="fa fa-caret-up"></i>
      </span>
    <% end %>
  </div>

<% end %>

<div class="large-section">



<div id="stats">

    <div class="row-fluid">
      <div class="span8">
        <h1>
          <%= @exile.name %>
        </h1>
      </div>

      <div class="span4">
        <%= link_to new_exile_path, class: "small right border-button" do %>
          <i class="fa fa-plus"></i> new<% end %>
        <% if can?(:update, @exile) %>
          <%= link_to edit_exile_path(@exile), class: "small right border-button" do %>
            <i class="fa fa-magic"></i> Edit
          <% end %>
        <% end %>
      </div>

      <% if false %>
      <div class="span4">

        <div class="stat">
          <span class="value"><%= @exile.photos.try(:count).to_i %></span>
          <span class="side-label">
            <span>screenshots</span>
          </span>
        </div>

        <div class="stat">
          <span class="value"><%= @exile.uniques.count %></span>
          <span class="side-label">
            <span>Unique</span>
            <span>items</span>
          </span>
        </div>
      </div>
      <% end %>
    </div>

</div>

<% if @exile.tagline.present? %>
  <p class="tagline"><%= @exile.tagline %></p>
<% end %>
</div>

<% if @exile.any_photos? %>
  <div class="large-section bordered-section clearfix">
    <% @exile.photos.each do |photo| %>
      <%= link_to photo, class: "left photo" do %>
        <%= image_tag @exile.resized_photo(photo, :b) %>
      <% end %>
    <% end %>

    <%= link_to "http://imgur.com/a/#{@exile.album_uid}", class: "imgur-album", target: "_blank" do %>
      <i class="fa fa-picture-o fa-3x"></i><br>
      View on Imgur
    <% end %>
  </div>
<% end %>

<% content_for :cover do %>
<div id="cover">

  <% if @exile.cover.present? %>
    <div class="faded-background" style="background-image: url(<%= @exile.cover %>)">
      <div class="overlay"></div>
    </div>
  <% end %>

  <div class="wrapper-l">
    <div class="row-fluid">
      <div class="span12">
        <div id="user-actions">

        </div>


      </div>
    </div>
  </div>

</div>

<% end %>

<% if @exile.description.present? %>
<div class="large-section bordered-section description text row-fluid">
  <%= to_html @exile.description %>
</div>
<% end %>

<% if @exile.gear_description.present? %>
<div class="large-section bordered-section description text row-fluid">
  <%= to_html @exile.gear_description %>
</div>
<% end %>

<% if @exile.uniques.any? || @exile.gear.any? %>
<div class="large-section bordered-section row-fluid">

  <h2>Gear</h2>

  <% @exile.uniques.each_slice(4) do |uniques| %>
    <div class="row-fluid">
      <% uniques.each do |unique| %>
        <%= link_to "http://pathofexile.gamepedia.com/#{unique.name}",
              target: "_blank",
              class: "span3 exile" do %>
            <div class="box-content">
              <h5><%= unique.name %></h5>
              <p class="text faded"><%= unique.base_name %></p>
              <%= image_tag unique.image_url %>
            </div>
        <% end %>
      <% end %>
    </div>
  <% end if @exile.uniques.any? %>

  <% if @exile.gear.any? %>
    <% @exile.gear.each_slice(4) do |gears| %>
      <div class="row-fluid">
        <% gears.each do |gear| %>
          <div class="span3 exile">
            <div class="box-content">
              <h5>
                <%= link_to gear[:name],
                      "http://pathofexile.gamepedia.com/#{gear[:name]}",
                      target: "_blank" %>
              </h5>
              <p class="text faded"><%= gear[:type] %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<% end %>

</div>

<div id="recent-exiles" class="large-section bordered-section row-fluid">
  <div class="span6">
    <% if @prev_exile %>
      <%= link_to exile_path(@prev_exile) do %>
        <div class="span1">
          <i class="fa fa-caret-left fa-2x"></i>
        </div>
        <div class="span11">
          <h3><%= @prev_exile.name %></h3>
          <%= @prev_exile.tagline %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="span6">
    <% if @next_exile %>
      <%= link_to exile_path(@next_exile) do %>
        <div class="span11">
          <h3><%= @next_exile.name %></h3>
          <%= @next_exile.tagline %>
        </div>
        <div class="span1">
          <i class="fa fa-caret-right fa-2x"></i>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<% javascript "jquery.colorbox" %>
<% stylesheet "colorbox" %>

<% content_for :dom_ready do %>
  App.Vote.setup();
  $(".photo").colorbox({ rel: "g1", maxWidth: '80%', maxHeight: '90%' })
<% end %>