config/routes.rb
Poesearch::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root to: "searches#new"

  resources :users, except: [:index] do
    member do
      post :generate_token
      get :link_character
      post :validate_account
    end
    collection do
      get :update_layout
    end
    resource :account
  end

  resources :searches, except: [:edit] do
    collection do
      get :favorite, as: :favorite
    end
  end

  resources :searches, except: [:edit]
  [:weapons, :armours, :misc].each do |type|
      resources :"#{type.to_s.singularize}_searches", except: [:edit]
  end

  resources :similar_searches

  resources :items, only: [:index, :show, :destroy] do
    member do
      post    :add_to_cart
      delete  :remove_from_cart
      post    :verify
    end
  end

  resource :shopping_cart

  resources :authentications, only: [:create, :destroy]

  resources :messages

  resources :players do
    member do
      put :mark_online
      put :mark_offline
    end
  end

  resources :accounts

  namespace :admin do
    root to: "admin#index"
    resources :searches
    resources :broadcasts
    resources :messages, only: [:index, :show]
    resources :scrawls
  end


  resources :exile_searches, path: "/exiles/search"

  resources :exiles do
    member do
      put :vote_up
    end
    collection do
      post :load_votes
    end
  end

  resources :forum_threads, path: "/threads", only: [:show]

  get "/feedback",  to: "feedback#index", as: :feedback
  get "/about/item_prices", to: "about#item_prices", as: :item_prices
  get "/about/search_by_price", to: "about#search_by_price", as: :search_by_price
  get "/about/faq", to: "about#faq", as: :faq

  match '/auth/:provider/callback' => 'authentications#create', via: :get
end

app/models/similar_search.rb
class SimilarSearch < Search
  before_save :set_minimum_mod_match
  attr_accessor :force_minimum_mod_match

  def set_minimum_mod_match
    if (minimum_mod_match.blank? ||
        minimum_mod_match <= 0 ||
        force_minimum_mod_match)

      self.minimum_mod_match = Elastic::SimilarItemSearch.similar_stats_count(
        self, optional_stats_count
      )
    end

    if minimum_mod_match > optional_stats_count
      self.minimum_mod_match = optional_stats_count
    end

    self.minimum_mod_match = 0 if minimum_mod_match < 0

    if minimum_mod_match > stats_count
      self.minimum_mod_match = stats_count
    end
  end

  def same_item_type
    true if self[:same_item_type] != false
  end
  alias_method :same_item_type?, :same_item_type

  def optional_stats_count
    stats.select { |s| s.mod_id && !s.required? && !s.excluded? }.count
  end

  def to_s
    archetype_name
  end

  def to_title
    archetype_name.pluralize
  end

  def archetype
    case
    when weapon?; 0
    when armour?; 1
    when misc?; 2
    end
  end

  def archetype_name
    case
    when weapon?; "Weapon"
    when armour?; "Armour"
    when misc?; "Misc"
    end
  end

  def unique?
    return false unless rarity
    rarity.name.downcase == "unique"
  end
end

app/controllers/similar_searches_controller.rb
class SimilarSearchesController < ApplicationController
  respond_to :html

  before_filter :find_search, only: [:show, :update]
  before_filter :view_layout, only: [:new, :show, :create]

  def new
    @form = SimilarSearchFormDecorator.new(nil)
  end

  def show
    search
  end

  def create
    text = params[:similar_search][:text_representation]
    league_id = params[:similar_search][:league_id].presence || current_league_id

    if text.blank?
      flash.now[:alert] = "The text representation of the item can't be blank"
      return render(:new)
    end

    begin
      parser = ItemParser.new(text)
      search = parser.search
      search.update_attribute(:league_id, league_id)
    rescue TypeError => e
      flash.now[:alert] = e.message
      return render(:new)
    rescue ItemParsers::Base::InvalidSearchError => e
      flash.now[:alert] = e.message
      return render(:new)
    end

    respond_with search, location: similar_search_path(search)
  end

  def update
    @search.update_attributes(params[:similar_search])
    respond_with @search
  end

  private

  def search
    session[:current_league_id] = @search.league_id

    @searchable = Elastic::SimilarItemSearch.new(@search, params)
    @tire_search = @searchable.tire_search
    @results = ItemDecorator.decorate_collection(
      @tire_search.results,
      context: { size: layout_size }
    )
    @form = SimilarSearchFormDecorator.new(@search)
  end

  def find_search
    @search = Search.find_by(uid: params[:id])
  end

end

app/views/similar_searches/new.html.erb
<%= page_title("Similar Search") %>

<%= render "searches/search_sub_header" %>

<%= simple_form_for :similar_search, { url: similar_searches_path } do |f| %>
  <div class="controls-row">
  <%= f.label :league_id, "League" %>
  <%= f.input :league_id,
      label: false,
      collection: simple_options_for_select(
        League,
        text: ->(name) { return nil unless League.visible?(name); name.capitalize + " league" }
      ),
      selected: current_league_id,
      input_html: { class: "span12 search_league" }
  %>
  </div>
  <%= f.input :text_representation, as: :text,
        label_html: { style: "margin-top: 20px" },
        label: "Text representation you get when copying an item in-game",
        input_html: { class: "span12", style: "height: 400px" } %>
  <%= f.button :submit, "Find similar items", class: "btn-success" %>
<% end %>

<% content_for :left_sidebar do %>
  <p class="text">
    In Path of Exile, when hovering over an item, pressing <code>Ctrl+C</code>
    will copy a text representation of the item in your clipboard. Paste it
    in the textarea, and PoExplorer will find similar items for you.
  </p>

  <p class="small text bordered-section">
    The most obvious use of this features is finding upgrades,
    since you can look for similar items with better stats.
    <br><br>
    It can also help you estimate the price of an item.
  </p>

  <p class="small text">
    This feature is in beta, don't hesitate to
    <%= link_to "report bugs, propose improvements, or ask questions", feedback_path %>.
  </p>
<% end %>

<% content_for :dom_ready do %>
  $("form select").select2();
<% end %>

app/views/similar_searches/show.html.erb
<%= page_title("#{@search.archetype_name} Search") %>

<%= render "searches/search_sub_header" %>

<%= render "searches/form" %>

<div class="alert alert-info">
  <p>
  Need your help to improve this feature!
  <%= link_to "Report any bug, and suggest improvements here", feedback_path %>.
  </p>
</div>

<%= render "searches/results_and_facets", no_facet_link: true %>

<% content_for :dom_ready do %>
  App.NumberFormatter.setup();
  App.SimilarMods.setup()
<% end %>

<% content_for :left_sidebar do %>
  <p class="text faded"><%= @searchable.explanation %></p>
<% end %>