config/routes.rb
Poesearch::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root to: "searches#new"

  resources :users, except: [:index] do
    member do
      post :generate_token
      get :link_character
      post :validate_account
    end
    collection do
      get :update_layout
    end
    resource :account
  end

  resources :searches, except: [:edit] do
    collection do
      get :favorite, as: :favorite
    end
  end

  resources :searches, except: [:edit]
  [:weapons, :armours, :misc].each do |type|
      resources :"#{type.to_s.singularize}_searches", except: [:edit]
  end

  resources :similar_searches

  resources :items, only: [:index, :show, :destroy] do
    member do
      post    :add_to_cart
      delete  :remove_from_cart
      post    :verify
    end
  end

  resource :shopping_cart

  resources :authentications, only: [:create, :destroy]

  resources :messages

  resources :players do
    member do
      put :mark_online
      put :mark_offline
    end
  end

  resources :accounts

  namespace :admin do
    root to: "admin#index"
    resources :searches
    resources :broadcasts
    resources :messages, only: [:index, :show]
    resources :scrawls
  end


  resources :exile_searches, path: "/exiles/search"

  resources :exiles do
    member do
      put :vote_up
    end
    collection do
      post :load_votes
    end
  end

  resources :forum_threads, path: "/threads", only: [:show]

  get "/feedback",  to: "feedback#index", as: :feedback
  get "/about/item_prices", to: "about#item_prices", as: :item_prices
  get "/about/search_by_price", to: "about#search_by_price", as: :search_by_price
  get "/about/faq", to: "about#faq", as: :faq

  match '/auth/:provider/callback' => 'authentications#create', via: :get
end

app/models/player.rb
class Player < ActiveRecord::Base
  include PlayerExtensions::Mapping

  ONLINE_DURATION = 1.5.hours

  attr_accessible :league_id, :character, :online

  belongs_to :league

  validates :account,   presence: true
  validates :account,   uniqueness: { scope: :character }
  validates :character, presence: true, uniqueness: true
  validates :online,    inclusion: { in: [true, false] }
  validates :league_id, presence: true

  scope :online,  -> { where(online: true) }
  scope :offline, -> { where(online: false) }

  scope :not_marked_online, -> { where("marked_online_at IS NULL OR marked_online_at < ?", ONLINE_DURATION.ago) }
  scope :updated_before,    ->(time) { where('updated_at < ?', time) }
  scope :updated_after,     ->(time) { where('updated_at > ?', time) }

  scope :by_league,    ->(league_id) { where(league_id: league_id) }
  scope :by_character, ->(character) { where(character: character) }
  scope :by_account,   ->(account) { where(account: account) }

  scope :in_league, ->(league_id) { where(league_id: league_id) }

  # not working, can't figure out why
  belongs_to :poe_account, primary_key: "account", foreign_key: "name", class_name: "Account"

  def self.create_from_api(player_data, league_id, version = 0)
    character_name = player_data["character"]["name"]
    account_name = player_data["account"]["name"]

    if Player.by_league(league_id).by_character(character_name).exists?
      return "NOT CREATED #{account_name} > #{character_name}"
    end

    player = Player.create do |player|
      player.character = character["name"]
      player.account = player_data["account"]["name"]
      player.league_id = league_id
      player.online = player_data["online"]
    end

    "player created #{player.account} > #{player.character}"
  end

  def self.create_all_from_api(players_data, league_id)
    formatted_data = players_data.map do |player|
      [
        player["account"]["name"],
        player["character"]["name"],
        league_id,
        player["online"],
        player["online"] ? Time.zone.now : nil
      ]
    end

    self.import(
      [:account, :character, :league_id, :online, :last_online],
      formatted_data
    )
  end

  def as_json(options = {})
    options[:except] ||= []
    options[:except] << :last_online

    options[:methods] ||= []
    options[:methods] << :last_online_iso8601
    options[:methods] << :marked_as_online

    super(options)
  end

  def last_online_iso8601
    last_online.try :iso8601
  end

  def online!
    self.online = true
    self.marked_online_at = Time.zone.now
    self.last_online = Time.zone.now
    save
  end
  def offline!
    self.online = false
    self.marked_online_at = nil
    save
  end

  def self.mark_offline(players, league_id = nil)
    return unless players

    players.update_all(
      online: false,
      marked_online_at: nil,
      updated_at: Time.zone.now
    )

    if league_id
      TireIndex.store(league_id, players)
    else
      players = players.to_a.sort_by! &:league_id
      chunks = players.chunk(&:league_id)
      chunks.each do |league_id, players|
        TireIndex.store(league_id, players)
      end
    end
  end

  def to_param
    character
  end

  def marked_as_online
    marked_online_at && marked_online_at > ONLINE_DURATION.ago
  end

  private

  def blank_character?
    character.blank?
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_filter :store_location

  before_filter :find_player, only: [:show, :edit, :update, :mark_online, :mark_offline, :destroy]
  before_filter :authorize_create, only: [:new, :create]
  before_filter :authorize_update, only: [:edit, :update, :mark_online, :mark_offline, :destroy]

  layout :layout_for_request
  respond_to :html, :json

  def index
    @players = Player.where(character: params[:characters])

    respond_with do |format|
      format.json { render json: @players }
      format.html { redirect_to root_path }
    end
  end

  def new
    @player = Player.new
    respond_with @player
  end

  def show
    if !@player
      return redirect_to root_url, notice: "This player couldn't be found on PoExplorer."
    end
    respond_with @player
  end

  def edit

  end

  def create
    @player = Player.new(params[:player]) do |p|
      p.account = current_user.account_name
    end

    @player.save
    set_other_player_as_offline if @player.online?

    respond_with @player, location: @player.errors.any? ? nil : current_user
  end

  def update
    @player.update_attributes(params[:player])
    @player.account = current_user.account_name

    @player.save
    set_other_player_as_offline if @player.online?

    respond_with current_user
  end

  def mark_online
    @player.online!
    set_other_player_as_offline

    respond_with current_user
  end

  def mark_offline
    @player.offline!

    respond_with current_user
  end

  def destroy
    @player.destroy
    respond_with @player, location: user_url(current_user)
  end

  private

  def new_player
    Player.new do |p|
      p.account = params[:id]
    end
  end

  def layout_for_request
    request.xhr? ? false : "application"
  end

  def find_player
    @player = Player.find_by(character: params[:id])
  end

  def authorize_create
    authorize! :create, Player
  end

  def authorize_update
    authorize! :update, @player
  end

  def set_other_player_as_offline
    Player.mark_offline(current_user.players.where('id <> ?', @player.id))
  end
end

app/views/players/_add.html.erb
<%= link_to new_player_path do %>
<div class="box span3" id="add-character">
  <div class="box-content">
    <h2>Add a character</h2>
    <i class="fa fa-plus fa-5x"></i>
  </div>
</div>
<% end %>

app/views/players/_form.html.erb
<%= simple_form_for @player do |f| %>
  <div class="bordered-section">
  <%= f.input :character, label: "Character name (IGN)" %>
  <%= f.input :league_id, label: "League",
          collection: League.running,
          selected: @player.league_id || current_league_id %>
  <%= f.input :online,
    label: "Mark online <i class='fa fa-circle online-icon online'></i>".html_safe %>
  </div>
  <%= f.button :submit, @player.new_record? ? "Create character" : "Update character", class: "btn btn-success" %>
<% end %>

app/views/players/_head.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="span3">
      Account
    </div>

    <div class="span3">
      Character
    </div>

    <div class="span2">
      League
    </div>

    <div class="span4">
      Actions
    </div>
  </div>
</div>

app/views/players/_player.html.erb
<div class="box span3">
  <div class="box-content dark">
    <h2>
      <i class="fa fa-circle right online-icon <%= player.online? ? "online" : "offline" %>"></i>
      <%= player.character %>
    </h2>
    <p class="small faded">
      played by
      <%= link_to player.account, account_path(player.account) %>
    </p>
  </div>

  <% if can? :edit, player %>
    <div class="box-content">
      <% if !player.online? %>
        <%= link_to mark_online_player_path(player), method: :put do %>
          Mark online
        <% end %>
      <% else %>
        <%= link_to mark_offline_player_path(player), method: :put do %>
          Mark offline
        <% end %>
      <% end %>
    </div>
  <% end %>

    <div class="box-content clearfix small">
      <% if league = player.league %>
        <% if league.hardcore? %>
          <i class="fa fa-shield"></i>
        <% end %>
        <%= league.name.titleize %>
      <% else %>
        n/a
      <% end %>
      <% if can? :edit, player %>
      <%= link_to player_path(player),
            class: "ttip right",
            title: "Destroy",
            method: :delete do %>
        <i class="fa fa-times"></i>
      <% end %>
      <%= link_to edit_player_path(player),
          class: "ttip right",
          title: "Edit" do %>
        <i class="fa fa-pencil"></i>&nbsp;&nbsp;
      <% end %>
      <% end %>
    </div>
</div>

app/views/players/_players_listing.html.erb
<%
players ||= []
add_character ||= false

if add_character
  players = players.unshift(Struct.new("AddPlayer") do
    def to_partial_path; "players/add" end
  end.new())
end
%>

<div class="section">

  <% if players.any? %>
    <% players.each_slice(4) do |slice| %>
      <div class="row-fluid">
        <%= render slice %>
      </div>
    <% end %>

  <% else %>
    <div class="no-results">
      <h2>No Characters</h2>
    </div>
  <% end %>
</div>

app/views/players/edit.html.erb
<%= render "form" %>

app/views/players/new.html.erb
<% content_for :left_sidebar do %>
  <h1>Add a Character</h1>
<% end %>

<%= render "form" %>

app/views/players/show.html.erb
<%= render "users/users_sub_header" %>

<h1><%= @player.character %></h1>
<p>Played by <%= @player.account %></p>