config/routes.rb
Poesearch::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root to: "searches#new"

  resources :users, except: [:index] do
    member do
      post :generate_token
      get :link_character
      post :validate_account
    end
    collection do
      get :update_layout
    end
    resource :account
  end

  resources :searches, except: [:edit] do
    collection do
      get :favorite, as: :favorite
    end
  end

  resources :searches, except: [:edit]
  [:weapons, :armours, :misc].each do |type|
      resources :"#{type.to_s.singularize}_searches", except: [:edit]
  end

  resources :similar_searches

  resources :items, only: [:index, :show, :destroy] do
    member do
      post    :add_to_cart
      delete  :remove_from_cart
      post    :verify
    end
  end

  resource :shopping_cart

  resources :authentications, only: [:create, :destroy]

  resources :messages

  resources :players do
    member do
      put :mark_online
      put :mark_offline
    end
  end

  resources :accounts

  namespace :admin do
    root to: "admin#index"
    resources :searches
    resources :broadcasts
    resources :messages, only: [:index, :show]
    resources :scrawls
  end


  resources :exile_searches, path: "/exiles/search"

  resources :exiles do
    member do
      put :vote_up
    end
    collection do
      post :load_votes
    end
  end

  resources :forum_threads, path: "/threads", only: [:show]

  get "/feedback",  to: "feedback#index", as: :feedback
  get "/about/item_prices", to: "about#item_prices", as: :item_prices
  get "/about/search_by_price", to: "about#search_by_price", as: :search_by_price
  get "/about/faq", to: "about#faq", as: :faq

  match '/auth/:provider/callback' => 'authentications#create', via: :get
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  before_filter :view_layout

  def item_prices

  end

  def price_search

  end

  def faq

  end

end

app/views/about/_about_sub_header.html.erb
<% content_for :h1 do %>
  <%= link_to "Help" %>
<% end %>

<% content_for :main_menu do %>
  <%= render "about/main_menu" %>
<% end %>

app/views/about/_help_sidebar.html.erb
<div class="facet">
  <ul>
    <li>
      <%= link_to "F.A.Q.", faq_path, class: "facet-title #{"current" if params[:action] == "faq"}" %>
    </li>
  </ul>
</div>

<div class="facet">
  <ul>
    <li><%= link_to "Search by item price", search_by_price_path, class: "facet-title #{"current" if params[:action] == "search_by_price"}" %></li>
    <li><%= link_to "Set item prices", item_prices_path, class: "facet-title #{"current" if params[:action] == "item_prices"}" %></li>
  </ul>
</div>

app/views/about/_main_menu.html.erb
<li class="tab-help"><%= link_to "Help", item_prices_path %></li>
<li class="tab-feedback"><%= link_to "Feedback", feedback_path %></li>

app/views/about/faq.html.erb
<%= render "about_sub_header" %>

<% content_for :left_sidebar do %>
<%= render "about/help_sidebar" %>
<% end %>

<div class="text bordered-section">
  <h2 class="first">F.A.Q.</h2>

  <p>I will add to this section at a future date, and might add some tutorials.</p>
</div>

<div class="text">
  <div class="bordered-section">
    <h3 class="first">Can you only show items with online sellers?</h3>

    <p>
      This feature wasn't available in the previous version of PoExplorer,
      but it now is! Just check the checkbox "Online only" in the
      search form, and you're set!
    </p>
  </div>

  <div class="bordered-section">
    <h3 class="first">My items are not indexed, what's happening?</h3>

    <p>
      Your threads are indexed when they reach the first pages in the forum.
      <br>
      I improved the indexing performances quite a bit in the new version
      of the site, and will continue to do so.
    </p>

    <p>Feel free to <%= link_to "contact me", feedback_path %> if you still have problems, and I'll make sure your stuff gets indexed.</p>
  </div>

</div>

app/views/about/item_prices.html.erb
<%= render "about_sub_header" %>

<% content_for :left_sidebar do %>
  <%= render "about/help_sidebar" %>
<% end %>

<div class="text">

  <div class="bordered-section">
    <h2 class="first">How to set prices in your PoE forum threads</h2>

    <p>
      This page details the format you should use to set
      the prices of your items in your forum threads.
    </p>
  </div>

  <div class="bordered-section clearfix">
    <h2>Price tag types</h2>

    <p><span class="tag">~gb/o</span> means "global buyout". <span class="tag">~b/o</span> means "buyout".</p>

    <div class="row_fluid">
      <div class="span4">
        <h3 class="unique">Global</h3>
        <p><span class="tag">~gb/o 2 chaos</span></p>
        <p>Set the price of all the items in the thread. The other 2 price tags have precedence over this one.</p>
      </div>

      <div class="span4">
        <h3 class="rare">Spoiler title</h3>
        <p><span class="tag">[spoiler="~b/o 2 chaos"][/spoiler]</span></p>
        <p>
          Set the price of the items listed within the spoiler.
          Nested spoilers are supported.
        </p>
      </div>

      <div class="span4">
        <h3 class="magic">Local</h3>
        <p><span class="tag">[item] ~b/o 2 chaos</span></p>
        <p>
          Set the price of the item listed just before the tag.
          Has precedence over the other 2 tags.
        </p>
      </div>
    </div>
  </div>

  <div class="bordered-section clearfix">
    <h2>Price tag format</h2>

    <p>The price defined as a unique value/currency pair: <span class="tag">[value (integer or float)] [currency name]</span></p>

    <h3>Examples</h3>
    <p><span class="tag">2 exalted</span>, <span class="tag">1.5 exa</span>, <span class="tag">15 chaos</span></p>
    <p><span class="tag">2 exalted 2 gcp</span> will be understood as <span class="tag">2 exalted</span></p>
  </div>

  <div class="bordered-section clearfix">
    <h2>Supported currencies</h2>

    <div class="row-fluid">
      <div class="span4">
        <p><span class="orb alch"></span> Alchemy orb: <span class="tag">alch</span></p>
        <p><span class="orb chaos"></span> Chaos orb: <span class="tag">chaos</span></p>
        <p><span class="orb gcp"></span> Gemcutter's Prism <span class="tag">gcp</span></p>
        <p><span class="orb exa"></span> Exalted orb: <span class="tag">exa</span></p>
      </div>
      <div class="span8">
        <p>I decided to support only 4 popular currencies because it will make the search by price easier and more perfomant.</p>

        <p>If you set a price in a different currency, it will simply be ignored.</p>
      </div>
    </div>
  </div>

  <div class="bordered-section clearfix">
    <h2>Thread example</h2>

    <pre>
[item]
<span class="tag">~b/o 1 gcprism</span>
This item costs 1 gcp.
As long as the currency name starts by the currency abbreviation,
it will be recognized.

[spoiler="Everything for less than 1 chaos! <span class="tag">~b/o 1 chaos</span>"]

  [item] This item costs 1 chaos
  [item] <span class="tag">~b/o 1 alchemy</span> This item costs 1 alch

  [spoiler="Nested spoiler, everything for 1 alch! <span class="tag">~b/o 1 alch</span>"]

    [item] This item costs 1 alch

  [/spoiler]

[/spoiler]

[item] This item costs 3 alch because of the global buyout

<span class="tag">~gb/o 3 alch</span>
All items without a buyout specified cost 3 alchs in this thread.
This can be placed anywhere.
    </pre>
  </div>
</div>

app/views/about/search_by_price.html.erb
<%= render "about_sub_header" %>

<% content_for :left_sidebar do %>
  <%= render "about/help_sidebar" %>
<% end %>

<div class="text">

  <div class="bordered-section">
    <h2 class="first">Searching by price</h2>

    <p>EDIT: VERY OUTDATED RATES.</p>

    <p>On PoExplorer, you can filter items by price.</p>

    <p>When you search for items which costs "At least 20 chaos", you want items that cost 1 exalted orb to show up, for example. For this to work, we need the current exchange rates.</p>

    <p>Right now, they are hard-coded, but later, I will use <%= link_to "http://exileex.com", "http://exileex.com" %> API to keep up to date.</p>
  </div>

  <style type="text/css">
      table td {
        text-align: center;
        vertical-align: middle;
        padding: 0 5px;
      }
    </style>

  <div class="bordered-section">
    <h2>Softcore League exchange rates</h2>

    <table class="big">
      <tr>
        <td></td>
        <td><span class="orb alch"></span></td>
        <td><span class="orb chaos"></span></td>
        <td><span class="orb gcp"></span></td>
        <td><span class="orb exa"></span></td>
      </tr>

      <tr>
        <td><span class="orb alch"></span></td>
        <td>1</td>
        <td>2:1</td>
        <td>7:1</td>
        <td>39:1</td>
      </tr>
      <tr>
        <td><span class="orb chaos"></span></td>
        <td>2:1</td>
        <td>1</td>
        <td>4:1</td>
        <td>34:1</td>
      </tr>
      <tr>
        <td><span class="orb gcp"></span></td>
        <td>1:7</td>
        <td>1:4</td>
        <td>1</td>
        <td>10:1</td>
      </tr>
      <tr>
        <td><span class="orb exa"></span></td>
        <td>1:39</td>
        <td>1:34</td>
        <td>1:10</td>
        <td>1</td>
      </tr>
    </table>
  </div>

  <div class="bordered-section">
    <h2>Hardcore League exchange rates</h2>

    <table class="big">
      <tr>
        <td></td>
        <td><span class="orb alch"></span></td>
        <td><span class="orb chaos"></span></td>
        <td><span class="orb gcp"></span></td>
        <td><span class="orb exa"></span></td>
      </tr>

      <tr>
        <td><span class="orb alch"></span></td>
        <td>1</td>
        <td>2:1</td>
        <td>5:1</td>
        <td>32:1</td>
      </tr>
      <tr>
        <td><span class="orb chaos"></span></td>
        <td>1:2</td>
        <td>1</td>
        <td>2:1</td>
        <td>20:1</td>
      </tr>
      <tr>
        <td><span class="orb gcp"></span></td>
        <td>1:5</td>
        <td>1:2</td>
        <td>1</td>
        <td>7:1</td>
      </tr>
      <tr>
        <td><span class="orb exa"></span></td>
        <td>1:32</td>
        <td>1:20</td>
        <td>1:7</td>
        <td>1</td>
      </tr>
    </table>
  </div>
</div>